#ifndef CONSTANTS_H
#define CONSTANTS_H

#define NUMBER_OF_REGIONS 5

#define IMPORTANT_SUBJECTS 5
#define OTHER_SUBJECTS 11
#define LANGUAGE_SUBJECTS 11
#define USELESS_SUBJECTS 2
#define TOTAL_SUBJECTS (IMPORTANT_SUBJECTS + OTHER_SUBJECTS + LANGUAGE_SUBJECTS)

#define MAX_NAME_LENGTH 20
#define EDUCATION_LIST_LENGTH 10
#define MAX_EDU_NAME_LENGTH 40

#define MAX_COMMAND_LENGTH 10
#define MAX_INPUT_LENGTH (MAX_COMMAND_LENGTH + 100)

#define NOT_IN_LIST -1
#define NO_EMPTY_INDEX -1

#define FIELD_SIZE 25

#define ADJUSTMENT_CONSTANT 0.1

#define DATABASE_PATH "./bin/data/database.txt"

#endif